version: '3.8'

services:
    swiftqueue_app:
        build:
            context: .
        expose:
            - 9000
        container_name: swiftqueue_app
        restart: always
        volumes:
            - ./app:/var/www/html/app:cached
            - ./routes:/var/www/html/routes:cached
            - ./database:/var/www/html/database:cached
            - ./resources:/var/www/html/resources:cached
            - ./composer.json:/var/www/html/composer.json:cached
            - ./composer.lock:/var/www/html/composer.lock:cached
        depends_on:
            - mysql
        networks:
            - laravel_network

    mysql:
        image: mysql:8
        container_name: mysql_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel_db
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: laravel_pass
        ports:
            - "3307:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - laravel_network

    nginx:
        image: nginx:latest
        container_name: nginx_server
        restart: always
        ports:
            - "8080:80"
        volumes:
            - ./app:/var/www/html/app:cached
            - ./routes:/var/www/html/routes:cached
            - ./resources:/var/www/html/resources:cached
            - ./public:/var/www/html/public:cached
            - ./laravel.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - swiftqueue_app
        networks:
            - laravel_network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: pma
        restart: always
        ports:
            - "8081:80"
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
        depends_on:
            - mysql
        networks:
            - laravel_network

networks:
    laravel_network:

volumes:
    mysql_data:
